### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by magdalko** [billneff79/recharts#5]
Hi, I tried to apply your changes as I need to use some mouse events on Brush and you have implemented it. But I wasn't successful. How to make your version working? Best wishes

**Comment by billneff79** [comment]
I'm not sure I understand the question.  Are you talking about my fork, or the master version at [recharts/recharts](https://github.com/recharts/recharts)?  I haven't maintained this fork at all and the changes I had I believe were incorporated back into the mainline repo.

**Comment by magdalko** [comment]
I mean excatly your code I found on this github account. I need to add onMouseUp event on Brush, while the original Recharts is not supporting it. That's how and why I found your code, but when I tried to implement it by myself it didn't completely work. Have no idea how to make it work and if possible to modify the original version of Recharts

**Comment by billneff79** [comment]
My fork is not active (it was merged into the mainline last year).  However, I might be able to point you in the right direction:
As you can see [here](https://github.com/recharts/recharts/blob/master/src/cartesian/Brush.js#L422), `Brush` is calling its internal `this.handleDragEnd` function to the `onMouseUp` call in `Layer`.  If you modify [`handleDragEnd`](https://github.com/recharts/recharts/blob/master/src/cartesian/Brush.js#L157-L162) in `Brush` to look like this, my guess is it would work:
```
  handleDragEnd = () => {
    this.setState({
      isTravellerMoving: false,
      isSlideMoving: false,
    });
    this.props.onMouseUp && this.props.onMouseUp(); //call the onMouseUp prop function if it exists
  };

```
